### ISSUE TITLE
4.3. 预申请机制

### ISSUE THREAD

**Issue by colinrs** [daemon-coder/idalloc#5]
这个预申请机制实在哪里实现的？是 func (a *ServiceAllocHandler) StartAsyncAlloc() 实现的么？我看这个代码的意思是，在申请ID时，如果不够，会使用 提前在 AsyncAllocChan 里面的数据。
好像并没有实现在 “当现有ID池中的ID快要耗尽时，异步申请线程会立即触发下一轮的ID申请”，而是 "不够了，直接拿之前生成的数据，没有生成就需要等待"

**Comment by daemon-coder** [comment]
你说的是对的，“当现有ID池中的ID快要耗尽时，异步申请线程会立即触发下一轮的ID申请” 这句话描述有误，正确的是『不够了，直接拿之前生成的数据，拿走之后立即触发下一轮的的ID申请』，也就是ID池中刚更新就会触发下一轮申请，而不是快耗尽时才触发。
